---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - typescript
  eslint:
    enabled: true
  tslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
  - "**.ts"
  - "**.tsx"
exclude_paths: []
